"""empty message

Revision ID: 06710b637e60
Revises: a29a9d2507f0
Create Date: 2022-06-09 12:45:07.667738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06710b637e60'
down_revision = 'a29a9d2507f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('association',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('channel_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('association')
    # ### end Alembic commands ###
